name: Code Review Approval

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check_plus_one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for +1 comment
        uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core');
            const github = require('@actions/github');

            const { owner, repo } = context.repo;
            const { number } = context.payload.pull_request;

            try {
              const comments = await github.issues.listComments({
                owner,
                repo,
                issue_number: number,
              });

              const hasPlusOne = comments.data.some(comment => comment.body.includes('+1'));

              if (!hasPlusOne) {
                core.setFailed('A "+1" comment is required for merging.');
              }
            } catch (error) {
              core.setFailed(`Error fetching comments: ${error.message}`);
            }
